routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('menu');
})->name('menu');
Route::middleware('auth')->group(function () {
    Route::get('/cook_presence', function () {
        return view('cook-presence');
    })->name('cook-presence');
    Route::get('/ingredients_update', function () {
        return view('ingredients-update');
    })->name('ingredients-update');
    Route::get('/orders', function () {
        return view('orders');
    })->name('orders');
});

app/Models/Cook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Orchid\Filters\Filterable;
use Orchid\Screen\AsSource;

class Cook extends Model
{
    use HasFactory, AsSource, Filterable;

    protected $guarded = [
        'id'
    ];

    protected $allowedFilters = [
        'id',
        'name',
        'is_present',
        'created_at',
        'updated_at',
    ];
    
    protected $allowedSorts = [
        'id',
        'name',
        'is_present',
        'created_at',
        'updated_at',
    ];

    protected $casts = [
        'is_present' => 'boolean',
    ];

    protected $with = [
    ];

    public function getProffessionAttribute(){
        return $this->cooking_type->title;
    }

    public function presence(){
        return [
            0 => 'Отсутствует',
            1 => 'Присутствует',
        ];
    }

    public function getPresenceAttribute(){
        return $this->presence()[$this->is_present];
    }

    public function cooking_type(){
        return $this->belongsTo(CookingType::class);
    }
}

app/Http/Livewire/CookPresence.php
<?php

namespace App\Http\Livewire;

use App\Models\Cook;
use App\Models\CookingType;
use Livewire\Component;

class CookPresence extends Component
{
    public function toggle_present(Cook $cook){
        $cook->update([
            'is_present' => !$cook->is_present
        ]);
    }

    private function getCookingTypes(){
        return CookingType::with('cooks')->get();
    }

    public function render()
    {
        return view('livewire.cook-presence', [
            'cooking_types' => $this->getCookingTypes()
        ]);
    }
}

app/Http/Livewire/IngredientsUpdate.php
<?php

namespace App\Http\Livewire;

use App\Models\Ingredient;
use Livewire\Component;

class IngredientsUpdate extends Component
{
    public $choosed_ingredients = [];

    public $search = "";

    public function choose($id){
        $filtering = array_search($id, array_column($this->choosed_ingredients, 'id'));
        if( is_int($filtering) ){
            unset($this->choosed_ingredients[$filtering]);
            $this->choosed_ingredients = array_merge($this->choosed_ingredients);
        }
        else{
            $this->choosed_ingredients[] = [
                'id' => $id,
                'count' => null,
                'price' => Ingredient::find($id)->price,
            ];
        }
    }

    private function getIngredients(){
        return Ingredient::when($this->search, function ($q){
            return $q->where('title', 'like', '%'.$this->search.'%');
        })->orderBy('unit_count')->get();
    }

    public function update(){
        foreach($this->choosed_ingredients as $ch_ing){
            $ing_to_update = Ingredient::find($ch_ing['id']);
            $ing_to_update->update([
                'unit_count' => $ing_to_update->unit_count+ intval($ch_ing['count'])
            ]);
            if($ing_to_update->price != intval( $ch_ing['price'] )){
                $ing_to_update->ingredient_prices()->create([
                    'price' => intval( $ch_ing['price'] )
                ]);
            }
        }
        $this->choosed_ingredients = [];
    }

    public function render()
    {
        return view('livewire.ingredients-update', [
            'ingredients' => $this->getIngredients(),
        ]);
    }
}

app/Http/Livewire/Menu.php
<?php

namespace App\Http\Livewire;

use App\Models\Category;
use App\Models\Menu as ModelsMenu;
use App\Models\Order;
use Livewire\Component;

class Menu extends Component
{
    public function order($id){
        $menu = ModelsMenu::find($id);
        $order = Order::create();
        $order->menus()->sync([
            $id => [
                'total_price' => $menu->price
            ]
        ]);
        $ingredients = $menu->ingredients()->get();
        foreach($ingredients as $ingredient){
            $ingredient->update([
                'unit_count' => $ingredient->unit_count - $ingredient->pivot->unit_count
            ]);
        }
    }

    public function render()
    {
        return view('livewire.menu', [
            'categories' => Category::with([
                'menus' => function ($menu){
                    return $menu
                        ->withCount([
                            'cooking_types' => function ($cooking_type){
                                return $cooking_type->whereRelation('cooks', 'cooks.is_present', true);
                            },
                            'ingredients' => function ($ingredient){
                                return $ingredient->whereColumn('ingredients.unit_count', '<', 'ingredient__menu.unit_count');
                            }
                        ])
                        ->having('cooking_types_count', '!=', 0)
                        ->having('ingredients_count', '==', 0)
                        ;
                },
            ])->get()
        ]);
    }
}

app/Http/Livewire/Orders.php
<?php

namespace App\Http\Livewire;

use App\Models\Order;
use Livewire\Component;

class Orders extends Component
{
    public function changeStatus($id, $status_key){
        Order::find($id)->update([
            'status' => $status_key
        ]);
    }

    public function render()
    {
        return view('livewire.orders', [
            'orders' => [
                0 => Order::where([
                    ['status', 0],
                    ['created_at', '>=',now()->subDay()],
                ])->get(),
                1 => Order::where([
                    ['status', 1],
                    ['created_at', '>=',now()->subDay()],
                ])->get(),
                2 => Order::where([
                    ['status', 2],
                    ['created_at', '>=',now()->subDay()],
                ])->get(),
            ],
        ]);
    }
}

resources/views/livewire/cook-presence.blade.php
<div class="flex flex-col">
@foreach ($cooking_types as $type)
  <div class="py-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 w-5/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 w-4/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Proffession
              </th>
              <th scope="col" class="px-6 py-3 w-2/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Presence
              </th>
              <th scope="col" class="px-6 py-3 w-1/12 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                Checkout
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            @foreach ($type->cooks as $cook)
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap">
                    <div class="text-sm font-medium text-gray-900">
                        {{ $cook->name }}
                    </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ $cook->proffession }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                        @if ($cook->is_present)
                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                {{ $cook->presence }}
                            </span>
                        @else
                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                {{ $cook->presence }}
                            </span>
                        @endif
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <input name="cook_presence_{{ $cook->id }}" wire:click="toggle_present({{ $cook->id }})" type="checkbox" {{ $cook->is_present?'checked':'' }}>
                    </td>
                </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endforeach
</div>

resources/views/livewire/ingredients-update.blade.php
<div class="flex justify-between">
  <div class="flex flex-col px-4">
    <div class="py-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <input type="text" wire:model="search" placeholder="Search" name="search" id="search" class="focus:ring-gray-100 focus:border-gray-100 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md">
        </div>
      </div>
    </div>
    <div class="py-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          @if ($ingredients->count())
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 w-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Ingredient
                </th>
                <th scope="col" class="px-6 py-3 w-20 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Count
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              @foreach ($ingredients as $ingredient)
                <tr wire:click="choose({{ $ingredient->id }})" class="cursor-pointer hover:bg-gray-100">
                  <td class="px-6 py-4 whitespace-nowrap">
                    {{ $ingredient->title }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm">
                    {{ $ingredient->unit_count }}
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
          @else
            <div class="px-6 py-3 bg-gray-50">
              Таких ингредиентов мы не знаем...
            </div>
          @endif
        </div>
      </div>
    </div>
  </div>
  <div class="flex flex-col px-4">
    @if ($choosed_ingredients)
    <div class="py-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          @foreach ($choosed_ingredients as $key => $ch_ing)
          <div class="px-6 py-3 bg-white">
            <label for="price" class="block text-sm font-medium text-gray-700">{{ $ingredients->find($ch_ing['id'])->title }}</label>
            <div class="mt-1 relative rounded-md shadow-sm">
              <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <span class="text-gray-500 sm:text-sm">
                  шт
                </span>
              </div>
              <input type="text" wire:model="choosed_ingredients.{{ $key }}.count" class="focus:ring-gray-100 focus:border-gray-100 block w-full pl-10 pr-12 sm:text-sm border-gray-300 rounded-md">
            </div>
            <div class="mt-1 relative rounded-md shadow-sm">
              <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <span class="text-gray-500 sm:text-sm">
                  Тг
                </span>
              </div>
              <input type="text" wire:model="choosed_ingredients.{{ $key }}.price" class="focus:ring-gray-100 focus:border-gray-100 block w-full pl-10 pr-12 sm:text-sm border-gray-300 rounded-md">
            </div>
          </div>
          @endforeach
        </div>
      </div>
    </div>
    <div class="py-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <button wire:click="update" class="ml-auto w-full sm:w-auto py-2 px-3 bg-gray-300 text-gray-900 hover:bg-gray-100 disabled:bg-gray-50 text-sm font-semibold rounded-md shadow focus:outline-none cursor-pointer">
          Update
        </button>
      </div>
    </div>
    @endif
  </div>
</div>

resources/views/livewire/menu.blade.php
<div class="flex flex-col" wire:poll.3000ms>
@foreach ($categories as $category)
  <div class="py-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="p-2 shadow overflow-hidden border-b border-gray-200 sm:rounded-lg bg-gray-50">
        <h2 class="text-center font-medium text-xl">{{ $category->title }}</h2>
        @if ($category->menus->count())
        <table class="mt-2 min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 w-3/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Image
              </th>
              <th scope="col" class="px-6 py-3 w-5/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Title
              </th>
              <th scope="col" class="px-6 py-3 w-2/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Price
              </th>
              <th scope="col" class="relative w-2/12 px-6 py-3">
                Actions
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            @foreach ($category->menus as $menu)
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {{ $menu->preview->url ? $menu->preview->url : 'No Preview' }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {{ $menu->title }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                        {{ $menu->price }}
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium">
                        <button wire:click="order({{ $menu->id }})" class="w-full sm:w-auto py-2 px-3 bg-gray-300 text-gray-900 hover:bg-gray-100 disabled:bg-gray-50 text-sm font-semibold rounded-md shadow focus:outline-none cursor-pointer">
                            Order
                        </button>
                    </td>
                </tr>
            @endforeach
          </tbody>
        </table>
        @else
            <h3 class="mt-2 text-center font-medium text-gray-500 tracking-wider">
                Блюда временно отсутвтуют
            </h3>
        @endif
      </div>
    </div>
  </div>
@endforeach
</div>

resources/views/livewire/orders.blade.php
<div class="flex flex-col" wire:poll.3000ms>
    @foreach ($orders as $key => $order_list)
      <div class="py-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="p-2 shadow overflow-hidden border-b border-gray-200 sm:rounded-lg bg-gray-50">
            <h2 class="text-center font-medium text-xl">{{ \App\Models\Order::status()[$key] }}</h2>
            @if ($order_list->count())
            <table class="mt-2 min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 w-2/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Id
                  </th>
                  <th scope="col" class="px-6 py-3 w-4/12 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Menu Items
                  </th>
                  <th scope="col" class="relative w-4/12 px-6 py-3">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                @foreach ($order_list as $order)
                    <tr>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                            {{ $order->id }}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                            {{ $order->menus->implode('title', ', ') }}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium">
                            <div class="inline-flex rounded-lg shadow-sm" role="group">
                                @foreach (\App\Models\Order::status() as $key => $title)
                                    <button wire:click="changeStatus({{ $order->id }}, {{ $key }})" type="button" class="py-2 px-4 text-sm font-medium {{ $key == $order->status ? 'bg-gray-600' : 'bg-gray-700' }} border-gray-600 text-white hover:text-white hover:bg-gray-600 focus:ring-blue-500 focus:text-white">
                                        {{ $title }}
                                    </button>
                                @endforeach
                            </div>
                        </td>
                    </tr>
                @endforeach
              </tbody>
            </table>
            @else
                <h3 class="mt-2 text-center font-medium text-gray-500 tracking-wider">
                    Заказы на сегодня отсутвтуют
                </h3>
            @endif
          </div>
        </div>
      </div>
    @endforeach
    </div>